"""Phase 1 — npm (node-semver) range semantics.

These table-driven tests pin :mod:`docker.npm_environment.semver_range` to the
exact strict-semver behaviour of the ``semver`` package bundled with the pinned
Node image (``node:24.18.0-trixie-slim`` → npm ``11.16.0``).  The ground-truth
table in ``tests/data/npm_range_fixtures.json`` was generated by running that
pinned ``semver`` against every range/version combination and records the
boolean ``semver.satisfies(version, range, { includePrerelease: false })``
result.
"""

from __future__ import annotations

import json
import sys
import unittest
from pathlib import Path

_THIS_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(_THIS_DIR.parent))

from docker.npm_environment import NpmRange, NpmRangeError, parse_range, satisfies
from docker.versioning.semver import SemverError, parse as parse_version

_FIXTURES_PATH = _THIS_DIR / "data" / "npm_range_fixtures.json"


def _load_fixtures() -> list[tuple[str, str, bool]]:
    return json.loads(_FIXTURES_PATH.read_text())


class TestNpmRangeFixtures(unittest.TestCase):
    """Every pinned-semver fixture must match the Python port exactly."""

    def test_fixture_table_matches_pinned_npm(self):
        fixtures = _load_fixtures()
        self.assertGreater(len(fixtures), 500)
        failures: list[tuple[str, str, bool, bool]] = []
        for range_text, version, expected in fixtures:
            with self.subTest(range=range_text, version=version):
                try:
                    got = satisfies(range_text, version)
                except Exception as exc:  # pragma: no cover - diagnostic
                    failures.append((range_text, version, expected, type(exc).__name__))
                    continue
                if got != expected:
                    failures.append((range_text, version, expected, got))
        self.assertEqual(
            failures,
            [],
            f"{len(failures)} fixture mismatches; first: {failures[:10]}",
        )


class TestNpmRangeApi(unittest.TestCase):
    def test_parse_range_returns_immutable_range(self):
        rng = parse_range("^1.2.3")
        self.assertIsInstance(rng, NpmRange)
        self.assertTrue(rng.matches(parse_version("1.5.0")))
        self.assertFalse(rng.matches(parse_version("2.0.0")))

    def test_satisfies_accepts_string_versions(self):
        self.assertTrue(satisfies("^1.2.3", "1.2.3"))
        self.assertFalse(satisfies("^1.2.3", "2.0.0"))

    def test_invalid_range_raises(self):
        for bad in ("not a range", "1.2.3.4", "^", "1.2.3 -", "v1.2.3"):
            with self.subTest(bad=bad):
                with self.assertRaises(NpmRangeError):
                    parse_range(bad)

    def test_invalid_version_raises(self):
        with self.assertRaises(SemverError):
            satisfies("^1.2.3", "latest")

    def test_comparator_operand_whitespace_is_normalized(self):
        # node-semver accepts ``>= 14.0.0`` and ``>=14.0.0`` identically; the
        # published Pi lock contains both ``>= 14.0.0`` and
        # ``^12.20 || >= 14.13`` forms.
        self.assertTrue(satisfies(">= 14.0.0", "14.0.0"))
        self.assertFalse(satisfies(">= 14.0.0", "13.9.9"))
        self.assertTrue(satisfies("^12.20 || >= 14.13", "12.20.0"))
        self.assertTrue(satisfies("^12.20 || >= 14.13", "16.0.0"))
        self.assertFalse(satisfies("^12.20 || >= 14.13", "14.0.0"))


if __name__ == "__main__":
    unittest.main()
