"""npm (node-semver) range parsing and satisfaction.

The assembler validates that every resolved lock version still satisfies the
parent's declared range *before* any network or filesystem effect.  npm
lockfiles record ranges in node-semver syntax, so this module ports the exact
desugaring rules of the ``semver`` package bundled with the pinned Node image
(``^``, ``~``, X-ranges, hyphen ranges, comparators, ``||``) plus node-semver's
prerelease opt-in rule.

Only strict (non-loose) syntax is accepted.  Ranges are matched against
:class:`docker.versioning.semver.SemanticVersion` values.

Provenance and known deviations (Phase 1 introspection, task 1.8)
---------------------------------------------------------------

* Ground truth: the fixture table ``tests/data/npm_range_fixtures.json`` was
  generated by the ``semver`` package bundled with npm ``11.16.0`` (the npm
  shipped by the pinned ``node:24.18.0-trixie-slim`` image) and records
  ``semver.satisfies(version, range, { includePrerelease: false })`` for every
  range/version pair.  The port passes all 713 rows.
* Upper bounds are emitted as ``<X.Y.Z`` rather than node-semver's
  ``<X.Y.Z-0``.  The two are behaviourally identical here because the
  prerelease opt-in rule already excludes every prerelease version whose
  (major, minor, patch) equals the upper-bound tuple.
* Strict syntax only: loose mode, ``v``-prefixed versions, and the
  ``>=0.0.0-0`` ``GTE0PRE`` collapse are intentionally unsupported and
  rejected before effects; lockfile ranges produced by npm never use them.
* The npm ``checkList`` predicate for ``os``/``cpu`` is ported exactly;
  ``libc`` platform constraints are rejected in this phase rather than
  silently ignored (see ``lockfile._reject_unsupported_fields``).
"""

from __future__ import annotations

import re
from dataclasses import dataclass

from docker.versioning.semver import SemanticVersion, SemverError, parse as _parse_version


class NpmRangeError(ValueError):
    """A range string is not valid strict node-semver syntax."""


# ── primitives ─────────────────────────────────────────────────────────


@dataclass(frozen=True)
class _Bound:
    """One primitive comparator after desugaring.

    ``op`` is one of ``"<"``, ``"<="``, ``">"``, ``">="``, ``"="``; a
    ``None`` version with op ``""`` represents the ANY comparator.
    """

    op: str
    version: SemanticVersion | None


def _satisfies_bound(bound: _Bound, version: SemanticVersion) -> bool:
    if bound.op == "":
        return True
    bv = bound.version
    assert bv is not None
    if bound.op == ">":
        return version > bv
    if bound.op == ">=":
        return version >= bv
    if bound.op == "<":
        return version < bv
    if bound.op == "<=":
        return version <= bv
    return version == bv  # "="


@dataclass(frozen=True)
class NpmRange:
    """A parsed range: OR of AND-branches of primitive bounds."""

    branches: tuple[tuple[_Bound, ...], ...]

    def matches(self, version: SemanticVersion) -> bool:
        """Return ``True`` when *version* satisfies this range."""
        for branch in self.branches:
            ok = True
            for bound in branch:
                if not _satisfies_bound(bound, version):
                    ok = False
                    break
            if not ok:
                continue
            # node-semver prerelease opt-in: a prerelease version only
            # satisfies a branch when some comparator with a prerelease
            # targets the same (major, minor, patch) tuple.
            if version.prerelease:
                allowed = False
                for bound in branch:
                    bv = bound.version
                    if bv is not None and bv.prerelease and (
                        bv.major == version.major
                        and bv.minor == version.minor
                        and bv.patch == version.patch
                    ):
                        allowed = True
                        break
                if not allowed:
                    continue
            return True
        return False


# ── token parsing helpers ──────────────────────────────────────────────

_X_IDENT = re.compile(r"^(?:0|[1-9]\d*|[xX*])$")
_BUILD_RE = re.compile(r"\+[0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*")
_OP_RE = re.compile(r"^(<=|>=|<|>|=)")
_COMPARATOR_TRIM_RE = re.compile(r"(\s*)(<=|>=|<|>|=)\s+(\S+)")


def _trim_comparator_spaces(branch: str) -> str:
    """Collapse whitespace between a comparator operator and its operand.

    node-semver accepts ``>= 14.0.0`` and ``>=14.0.0`` identically (the
    published Pi lock contains both ``>= 14.0.0`` and ``^12.20 || >= 14.13``
    forms), so the strict port normalizes that spacing before splitting the
    branch into comparator tokens.
    """
    return _COMPARATOR_TRIM_RE.sub(r"\1\2\3", branch)


def _is_x(value: str | None) -> bool:
    return value is None or value == "" or value.lower() == "x" or value == "*"


def _strip_build(text: str) -> str:
    return _BUILD_RE.sub("", text)


def _parse_xparts(token: str) -> tuple[str, str | None, str | None, str | None, str | None]:
    """Split one X-range token into ``(gtlt, M, m, p, prerelease)``.

    Each of ``M``/``m``/``p`` is a digit string, ``"x"``/``"X"``/``"*"``, or
    ``None`` when absent.
    """
    token = token.strip()
    gtlt = ""
    rest = token
    op_match = _OP_RE.match(token)
    if op_match:
        gtlt = op_match.group(1)
        rest = token[op_match.end():].strip()

    base, sep, pre = rest.partition("-")
    if sep and not pre:
        raise NpmRangeError(f"invalid range token: {token!r}")
    parts = base.split(".")
    if len(parts) > 3:
        raise NpmRangeError(f"invalid range token: {token!r}")
    m = parts[0] if len(parts) >= 1 and parts[0] else None
    mi = parts[1] if len(parts) >= 2 else None
    p = parts[2] if len(parts) >= 3 else None
    for comp in (m, mi, p):
        if comp is not None and not _X_IDENT.match(comp):
            raise NpmRangeError(f"invalid range token: {token!r}")
    return gtlt, m, mi, p, pre or None


# ── desugaring (mirrors node-semver) ───────────────────────────────────


def _replace_caret(gtlt: str, M: str | None, m: str | None, p: str | None, pr: str | None) -> str:
    if gtlt:
        return ""  # caret must be the whole token (no operator)
    if M is None or _is_x(M):
        return ""
    if m is None or _is_x(m):
        return f">={M}.0.0 <{int(M) + 1}.0.0-0"
    if p is None or _is_x(p):
        if M == "0":
            return f">={M}.{m}.0 <{M}.{int(m) + 1}.0-0"
        return f">={M}.{m}.0 <{int(M) + 1}.0.0-0"
    if pr:
        if M == "0":
            if m == "0":
                return f">={M}.{m}.{p}-{pr} <{M}.{m}.{int(p) + 1}-0"
            return f">={M}.{m}.{p}-{pr} <{M}.{int(m) + 1}.0-0"
        return f">={M}.{m}.{p}-{pr} <{int(M) + 1}.0.0-0"
    if M == "0":
        if m == "0":
            return f">={M}.{m}.{p} <{M}.{m}.{int(p) + 1}-0"
        return f">={M}.{m}.{p} <{M}.{int(m) + 1}.0-0"
    return f">={M}.{m}.{p} <{int(M) + 1}.0.0-0"


def _replace_tilde(gtlt: str, M: str | None, m: str | None, p: str | None, pr: str | None) -> str:
    if gtlt:
        return ""
    if M is None or _is_x(M):
        return ""
    if m is None or _is_x(m):
        return f">={M}.0.0 <{int(M) + 1}.0.0-0"
    if p is None or _is_x(p):
        return f">={M}.{m}.0 <{M}.{int(m) + 1}.0-0"
    if pr:
        return f">={M}.{m}.{p}-{pr} <{M}.{int(m) + 1}.0-0"
    return f">={M}.{m}.{p} <{M}.{int(m) + 1}.0-0"


def _replace_xrange(
    gtlt: str, M: str | None, m: str | None, p: str | None, pr: str | None, original: str
) -> str:
    xM = _is_x(M)
    xm = xM or _is_x(m)
    xp = xm or _is_x(p)
    any_x = xp

    if gtlt == "=" and any_x:
        gtlt = ""
    pr = ""  # includePrerelease=False

    if xM:
        if gtlt in (">", "<"):
            return "<0.0.0-0"
        return "*"
    if M is None:
        return original
    if gtlt and any_x:
        m_val = 0 if (m is None or xm) else int(m)
        p_val = 0
        if gtlt == ">":
            gtlt = ">="
            if m is None or xm:
                M = str(int(M) + 1)
                m_val = 0
            else:
                m_val = int(m) + 1
            p_val = 0
        elif gtlt == "<=":
            gtlt = "<"
            if m is None or xm:
                M = str(int(M) + 1)
            else:
                m_val = int(m) + 1
        if gtlt == "<":
            pr = "-0"
        return f"{gtlt}{M}.{m_val}.{p_val}{pr}"
    if m is None or xm:
        return f">={M}.0.0{pr} <{int(M) + 1}.0.0-0"
    if p is None or xp:
        return f">={M}.{m}.0{pr} <{M}.{int(m) + 1}.0-0"
    return original


def _replace_hyphen(branch: str) -> str:
    parts = branch.split()
    # node-semver HYPHENRANGE is anchored to the whole branch: exactly
    # ``A - B``.
    if len(parts) == 3 and parts[1] == "-":
        from_tok, to_tok = parts[0], parts[2]
        _fg, fM, fm, fp, fpr = _parse_xparts(from_tok)
        _tg, tM, tm, tp, tpr = _parse_xparts(to_tok)
        if _fg or _tg:
            raise NpmRangeError(f"invalid hyphen range: {branch!r}")
        if fM is None or _is_x(fM):
            from_s = ""
        elif fm is None or _is_x(fm):
            from_s = f">={fM}.0.0"
        elif fp is None or _is_x(fp):
            from_s = f">={fM}.{fm}.0"
        elif fpr:
            from_s = f">={fM}.{fm}.{fp}-{fpr}"
        else:
            from_s = f">={fM}.{fm}.{fp}"

        if tM is None or _is_x(tM):
            to_s = ""
        elif tm is None or _is_x(tm):
            to_s = f"<{int(tM) + 1}.0.0-0"
        elif tp is None or _is_x(tp):
            to_s = f"<{tM}.{int(tm) + 1}.0-0"
        elif tpr:
            to_s = f"<={tM}.{tm}.{tp}-{tpr}"
        else:
            to_s = f"<={tM}.{tm}.{tp}"
        return f"{from_s} {to_s}".strip()
    return branch


def _desugar_token(token: str) -> list[str]:
    """Desugar one comparator token into primitive comparator strings."""
    token = _strip_build(token.strip())
    if not token:
        return [""]

    # Caret / tilde are whole-token prefixes.
    if token.startswith("^"):
        operand = token[1:].strip()
        if not operand:
            raise NpmRangeError(f"invalid range token: {token!r}")
        gtlt, M, m, p, pr = _parse_xparts(operand)
        if gtlt:
            raise NpmRangeError(f"invalid range token: {token!r}")
        token = _replace_caret("", M, m, p, pr)
    elif token.startswith("~"):
        operand = token[1:].strip()
        if not operand:
            raise NpmRangeError(f"invalid range token: {token!r}")
        if operand.startswith(">"):
            operand = operand[1:].strip()
        if not operand:
            raise NpmRangeError(f"invalid range token: {token!r}")
        gtlt, M, m, p, pr = _parse_xparts(operand)
        if gtlt:
            raise NpmRangeError(f"invalid range token: {token!r}")
        token = _replace_tilde("", M, m, p, pr)

    result: list[str] = []
    for part in token.split():
        part = part.strip()
        if not part:
            result.append("")
            continue
        gtlt, M, m, p, pr = _parse_xparts(part)
        if gtlt and M is None:
            raise NpmRangeError(f"invalid range token: {token!r}")
        part = _replace_xrange(gtlt, M, m, p, pr, part)
        result.append(part)
    token = " ".join(result)

    # Stars and >=0.0.0 collapse to ANY.
    final: list[str] = []
    for part in token.split():
        part = _strip_build(part.strip())
        if re.fullmatch(r"(?:<|>)?=?\s*\*", part) or part == ">=0.0.0":
            part = ""
        if part:
            final.append(part)
    if not final:
        return [""]
    return final


_COMPARATOR_RE = re.compile(r"^(<=|>=|<|>|=)?(.*)$")


def _parse_comparator(comp: str) -> _Bound:
    comp = comp.strip()
    match = _COMPARATOR_RE.match(comp)
    if not match:
        raise NpmRangeError(f"invalid comparator: {comp!r}")
    op = match.group(1) or ""
    version_str = match.group(2).strip()
    if op == "=":
        op = ""
    if not version_str:
        return _Bound("", None)  # ANY
    if version_str.startswith("v"):
        raise NpmRangeError(f"invalid comparator: {comp!r}")
    try:
        version = _parse_version(version_str)
    except SemverError as exc:
        raise NpmRangeError(f"invalid comparator: {comp!r}") from exc
    return _Bound(op or "=", version)


# ── public API ─────────────────────────────────────────────────────────


def parse_range(text: str) -> NpmRange:
    """Parse strict node-semver *text* into a :class:`NpmRange`."""
    if not isinstance(text, str):
        raise NpmRangeError(f"range must be a string, got {type(text).__name__!r}")
    stripped = _strip_build(text.strip())
    branches: list[tuple[_Bound, ...]] = []
    for branch in stripped.split("||"):
        branch = " ".join(branch.split())
        branch = _replace_hyphen(branch)
        branch = _trim_comparator_spaces(branch)
        bounds: list[_Bound] = []
        for token in branch.split():
            for comp in _desugar_token(token):
                bounds.append(_parse_comparator(comp))
        # Empty branch (or one that collapsed) is ANY.
        if not bounds:
            bounds = [_Bound("", None)]
        branches.append(tuple(bounds))
    if not branches:
        raise NpmRangeError(f"invalid range: {text!r}")
    return NpmRange(tuple(branches))


def satisfies(range_text: str, version_text: str) -> bool:
    """Return ``True`` when *version_text* satisfies *range_text*.

    Raises :class:`NpmRangeError` for an invalid range and
    :class:`docker.versioning.semver.SemverError` for an invalid version.
    """
    version = _parse_version(version_text)
    return parse_range(range_text).matches(version)
