"""Pi consumer launcher construction and evidence.

The assembler deliberately creates no executable link and no consumer-specific
layout.  This module is the Pi consumer: it selects ``bin.pi`` from the exact
reviewed ``@earendil-works/pi-coding-agent`` root metadata keyed by package
identity and resolved lock path (never from another reviewed root, never by
reparsing raw package input), resolves the target through the assembled
filesystem with no-follow-aware containment checks, and derives a deterministic
launcher plus consumer evidence for its exact contents, non-writable executable
mode, target, and containment.
"""
from __future__ import annotations

import hashlib
import json
import os
import re
from dataclasses import dataclass
from pathlib import Path, PurePosixPath

from docker.npm_environment import ReviewedRootMetadata, ValidatedAssemblyInput

# The launcher lives at /opt/pi/bin/pi inside the built image.
LAUNCHER_PATH = "/opt/pi/bin/pi"
LAUNCHER_MODE = 0o555

# The authoritative launcher-evidence schema: exactly these five fields.
_LAUNCHER_EVIDENCE_KEYS = frozenset({
    "launcher_path",
    "contents_sha256",
    "mode",
    "target",
    "containment",
})

_SHA256_HEX = re.compile(r"[0-9a-f]{64}\Z")


class PiConsumerError(RuntimeError):
    """Pi launcher selection, containment, or evidence failure."""


def _sha256_hex(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _validate_relative_target(target: object) -> str:
    """Require a non-empty relative POSIX path with no absolute/escaping form."""
    if not isinstance(target, str) or not target:
        raise PiConsumerError("launcher evidence target is missing or empty")
    if "\x00" in target:
        raise PiConsumerError("launcher evidence target contains a NUL byte")
    if target.startswith("/") or "\\" in target:
        raise PiConsumerError(
            f"launcher evidence target {target!r} is not a relative POSIX path"
        )
    parts = PurePosixPath(target).parts
    if not parts or ".." in parts:
        raise PiConsumerError(
            f"launcher evidence target {target!r} escapes its base"
        )
    return target


def _launcher_script(relative_target: str) -> bytes:
    """Render the canonical launcher for an environment-relative target."""
    launcher_target = f"../{relative_target}"
    return (
        "#!/bin/sh\n"
        "set -eu\n"
        "# Generated by docker-constructor; do not edit.\n"
        'self="$0"\n'
        'while [ -L "$self" ]; do\n'
        '  dir=$(CDPATH= cd -- "$(dirname -- "$self")" && pwd -P)\n'
        '  link=$(readlink "$self")\n'
        '  case "$link" in\n'
        '    /*) self="$link" ;;\n'
        '    *) self="$dir/$link" ;;\n'
        '  esac\n'
        'done\n'
        'base=$(CDPATH= cd -- "$(dirname -- "$self")" && pwd -P)\n'
        f'exec node "$base/{launcher_target}" "$@"\n'
    ).encode("utf-8")


def select_pi_metadata(
    validated: ValidatedAssemblyInput, *, package: str,
) -> ReviewedRootMetadata:
    """Return the exact reviewed-root metadata for *package*.

    Fails when the package is absent or resolves to more than one root, so
    metadata from one reviewed root can never stand in for another.
    """
    matches = [m for m in validated.root_metadata if m.package_name == package]
    if not matches:
        raise PiConsumerError(
            f"reviewed root {package!r} has no preserved metadata"
        )
    if len(matches) > 1:
        raise PiConsumerError(
            f"reviewed root {package!r} resolves to multiple lock paths: "
            + ", ".join(sorted(m.lock_path for m in matches))
        )
    return matches[0]


def resolve_contained_target(
    environment_root: str | Path, lock_path: str, bin_target: str,
) -> Path:
    """Resolve ``environment_root / lock_path / bin_target`` through symlinks.

    The result must remain contained within *environment_root* and be a regular
    file.  A dangling target, an escaping symlink chain, a directory, or any
    non-regular file is rejected.
    """
    environment_path = Path(environment_root)
    root = Path(os.path.realpath(os.fspath(environment_path)))
    candidate = Path(
        os.path.realpath(os.fspath(environment_path / Path(lock_path) / bin_target))
    )
    if candidate == root or root not in candidate.parents:
        raise PiConsumerError(
            f"launcher target {candidate} escapes the Pi environment {root}"
        )
    if not candidate.is_file():
        raise PiConsumerError(
            f"launcher target {candidate} is dangling or not a regular file"
        )
    return candidate


@dataclass(frozen=True)
class LauncherPlan:
    """Immutable launcher contents plus the resolved safe relative target."""

    contents: bytes
    target: str
    """Resolved target relative to the Pi environment root (e.g.
    ``node_modules/<pkg>/dist/bundle/cli.js``)."""
    mode: int = LAUNCHER_MODE


def plan_launcher(
    metadata: ReviewedRootMetadata, *, environment_root: str | Path,
) -> LauncherPlan:
    """Derive launcher contents and resolved target from one reviewed root.

    Consumes ``bin.pi`` only from *metadata* (keyed to the selected root's
    identity and resolved lock path).  The launcher is a fixed shell script
    that resolves its target relative to itself and execs ``node``.
    """
    bin_map = dict(metadata.bin)
    if "pi" not in bin_map:
        raise PiConsumerError("selected Pi root declares no 'pi' bin entry")
    bin_target = bin_map["pi"]
    resolved = resolve_contained_target(
        environment_root, metadata.lock_path, bin_target,
    )
    root = Path(os.path.realpath(os.fspath(environment_root)))
    relative = resolved.relative_to(root).as_posix()
    # The launcher sits in /opt/pi/bin, so the environment-relative target is
    # one directory up from the launcher's own directory (rendered by
    # ``_launcher_script``); the script resolves its own real location first so
    # a symlink at /usr/local/bin/pi still finds the assembled tree.
    return LauncherPlan(contents=_launcher_script(relative), target=relative)


@dataclass(frozen=True)
class LauncherEvidence:
    """Deterministic consumer-launcher evidence plus its digest.

    Carries the five validated schema fields alongside the exact serialized
    bytes and their digest, so evidence generation and strict parsing share one
    authoritative schema.
    """

    launcher_path: str
    contents_sha256: str
    mode: int
    target: str
    containment: bool
    data: bytes
    digest: str


def launcher_evidence(plan: LauncherPlan) -> LauncherEvidence:
    """Serialize and digest the consumer-launcher evidence body."""
    body = {
        "launcher_path": LAUNCHER_PATH,
        "contents_sha256": _sha256_hex(plan.contents),
        "mode": plan.mode,
        "target": plan.target,
        "containment": True,
    }
    data = json.dumps(body, sort_keys=True, separators=(",", ":")).encode("utf-8")
    return LauncherEvidence(
        launcher_path=body["launcher_path"],
        contents_sha256=body["contents_sha256"],
        mode=body["mode"],
        target=body["target"],
        containment=body["containment"],
        data=data,
        digest=_sha256_hex(data),
    )


def parse_launcher_evidence(data: bytes) -> LauncherEvidence:
    """Strictly parse the launcher evidence against the shared schema.

    Requires exactly the five evidence fields (rejecting both missing and
    unknown keys) and validates each value: ``launcher_path`` equals the
    canonical launcher location, ``contents_sha256`` is a lowercase 64-hex
    SHA-256 value, ``mode`` is the non-writable executable mode, ``target`` is
    a non-empty relative POSIX path with no absolute or escaping form, and
    ``containment`` is ``True``.  Use :func:`validate_launcher_evidence` to
    also re-bind the contents and resolve the target.
    """
    try:
        body = json.loads(data.decode("utf-8"))
    except (UnicodeDecodeError, json.JSONDecodeError) as exc:
        raise PiConsumerError(f"launcher evidence is not valid JSON: {exc}") from exc
    if not isinstance(body, dict):
        raise PiConsumerError("launcher evidence is not a JSON object")
    keys = set(body)
    if keys != _LAUNCHER_EVIDENCE_KEYS:
        missing = sorted(_LAUNCHER_EVIDENCE_KEYS - keys)
        unknown = sorted(keys - _LAUNCHER_EVIDENCE_KEYS)
        problems = []
        if missing:
            problems.append("missing field(s): " + ", ".join(missing))
        if unknown:
            problems.append("unknown field(s): " + ", ".join(unknown))
        raise PiConsumerError("launcher evidence " + "; ".join(problems))
    launcher_path = body["launcher_path"]
    if launcher_path != LAUNCHER_PATH:
        raise PiConsumerError(
            f"launcher evidence launcher_path {launcher_path!r} "
            f"does not equal {LAUNCHER_PATH!r}"
        )
    contents_sha256 = body["contents_sha256"]
    if not isinstance(contents_sha256, str) or not _SHA256_HEX.fullmatch(
        contents_sha256
    ):
        raise PiConsumerError(
            "launcher evidence contents_sha256 is not a lowercase "
            "64-character SHA-256 value"
        )
    mode = body["mode"]
    if not isinstance(mode, int) or isinstance(mode, bool) or mode != LAUNCHER_MODE:
        raise PiConsumerError(
            f"launcher evidence mode {mode!r} is not the non-writable "
            f"executable mode {LAUNCHER_MODE:#o}"
        )
    target = _validate_relative_target(body["target"])
    if body["containment"] is not True:
        raise PiConsumerError("launcher evidence containment is not True")
    return LauncherEvidence(
        launcher_path=launcher_path,
        contents_sha256=contents_sha256,
        mode=mode,
        target=target,
        containment=True,
        data=data,
        digest=_sha256_hex(data),
    )


def validate_launcher_evidence(
    data: bytes,
    *,
    launcher_contents: bytes,
    environment_root: str | Path,
) -> LauncherEvidence:
    """Fully validate launcher evidence against contents and environment.

    Strictly parses the evidence (:func:`parse_launcher_evidence`), requires
    the recorded contents digest to match *launcher_contents*, recomputes the
    canonical launcher script from the evidenced target and requires
    byte-for-byte equality (arbitrary bytes are never accepted merely for
    digest agreement), and resolves the target against *environment_root* as a
    contained regular file.
    """
    evidence = parse_launcher_evidence(data)
    if evidence.contents_sha256 != _sha256_hex(launcher_contents):
        raise PiConsumerError("launcher contents do not match the launcher evidence")
    if launcher_contents != _launcher_script(evidence.target):
        raise PiConsumerError(
            "launcher contents are not the canonical script for the evidenced target"
        )
    resolve_contained_target(environment_root, "", evidence.target)
    return evidence


def write_launcher(plan: LauncherPlan, destination: Path) -> Path:
    """Write the launcher with its non-writable executable mode."""
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_bytes(plan.contents)
    os.chmod(destination, plan.mode)
    return destination


__all__ = [
    "LAUNCHER_MODE",
    "LAUNCHER_PATH",
    "LauncherEvidence",
    "LauncherPlan",
    "PiConsumerError",
    "launcher_evidence",
    "parse_launcher_evidence",
    "plan_launcher",
    "resolve_contained_target",
    "select_pi_metadata",
    "validate_launcher_evidence",
    "write_launcher",
]
