shortprompt=true
bg_p_color=33
end_p='>'
title_u=''
title_h=''
title_d='%15<...<%1~'
if [[ -z $XAUTHORITY ]]; then
    title_h='%m:'
    title_d=''
fi

case $USER in
    (root)
	bg_p_color=31
	end_p='#'
	title_u='Root'
        title_d=''
	;;
    (*)
	shortprompt=false
	title_u=$USER
	;;
esac

s="%{"$'\e['
e="m%}"

# start sequence. set bold and reverse, color would be background one.
PS1="${s}01;07;$bg_p_color;"
if [[ $shortprompt != 'true' ]]; then
    # show username
    PS1=${PS1}"42${e}%n${s}46${e}@${s}"
fi
# show hostname, error if there is one and '>' or '#'
PS1=${PS1}"40${e}%m${s}00;31$e%(?..(%?%))${s}01;$bg_p_color$e$end_p${s}00${e}"

RPS1="[${s}01;$bg_p_color;40${e}%40<...<%~${s}00;39;49${e}]"

unset s e bg_p_color end_p

title=$title_u

if [[ -n $title_u && -n $title_h ]]; then
    title=${title}'@'
fi

title=${title}${title_h}

if [[ -n $title_h && -n $title_d ]]; then
    title=${title}':'
fi

title=${title}${title_d}

print_title() {
    [[ -t 1 ]] || return
    case $TERM in
	(sun-cmd|cygwin) print -Pn "\e]l$1\e\\"
	    ;;
	(*xterm*|rxvt|(dt|k|E)term) print -Pn "\e]2;$1\a"
	    ;;
    esac
}

precmd() {
    [[ -t 1 ]] || return
	print_title "$title"
}

unset title_u title_h title_d

alias ls='ls --color=auto'
alias ll='ls -l --color=auto'
alias l.='ls -a --color=auto'
